const ADD_MESSAGE = 'ADD_MESSAGE';
const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
const ADD_USER = 'ADD_USER';
const INITIALISE_USER = 'INITIALISE_USER';
const ATTACH_KEYS_TO_USER = 'ATTACH_KEYS_TO_USER';
const STORE_LOCAL_USER = 'STORE_LOCAL_USER';
const USERS_LIST = 'USERS_LIST';

export {ADD_MESSAGE, MESSAGE_RECEIVED, ADD_USER, INITIALISE_USER, ATTACH_KEYS_TO_USER, STORE_LOCAL_USER, USERS_LIST}
