const ADD_MESSAGE = 'ADD_MESSAGE';
const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
const ADD_USER = 'ADD_USER';
const INITIALISE_USER = 'INITIALISE_USER';
const CREATE_USER_FROM_KEYS = 'CREATE_USER_FROM_KEYS';
const USERS_LIST = 'USERS_LIST';

export {ADD_MESSAGE, MESSAGE_RECEIVED, ADD_USER, INITIALISE_USER, CREATE_USER_FROM_KEYS, USERS_LIST}
